x11: Fix broken `-c -o` test in configure script
Recent versions of gcc now consider it an error to declare a function
without a return type, so `foo(){}` is no longer a valid function
definition. The following is an example from `config.log`:
```
configure:3812: checking whether gcc understand -c and -o together
configure:3824: gcc -c conftest.c -o conftest.ooo 1>&5
conftest.c:1:1: error: return type defaults to 'int' [-Wimplicit-int]
    1 | foo(){}
      | ^~~
configure:3827: $? = 1
configure:3861: result: no
```
Thus, this test was always failing even though gcc obviously handles the
`-c` and `-o` options together. Adding a return type fixes the bug.